### ISSUE TITLE
Trackback Error

### ISSUE THREAD

**Issue by eichmmar** [leeroybrun/glacier-vault-remove#36]
I always get the following error message:
```
INFO : Removing 76480 archives... please be patient, this may take some time...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\...\AppData\Local\Programs\Python\Python36-32\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\...\AppData\Local\Programs\Python\Python36-32\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "C:\...\AppData\Local\Programs\Python\Python36-32\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\...\AppData\Local\Programs\Python\Python36-32\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\...\AppData\Local\Programs\Python\Python36-32\lib\runpy.py", line 263, in run_path
Traceback (most recent call last):
  File "C:\...\Documents\GitHub\glacier-vault-remove\removeVault.py", line 174, in <module>
    pkg_name=pkg_name, script_name=fname)
    p.start()
  File "C:\...\AppData\Local\Programs\Python\Python36-32\lib\runpy.py", line 96, in _run_module_code
  File "C:\...\AppData\Local\Programs\Python\Python36-32\lib\multiprocessing\process.py", line 105, in start
    mod_name, mod_spec, pkg_name, script_name)
    self._popen = self._Popen(self)
  File "C:\...\AppData\Local\Programs\Python\Python36-32\lib\runpy.py", line 85, in _run_code
  File "C:\...\AppData\Local\Programs\Python\Python36-32\lib\multiprocessing\context.py", line 223, in _Popen
    exec(code, run_globals)
  File "C:\...\Documents\GitHub\glacier-vault-remove\removeVault.py", line 174, in <module>
    p.start()
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\...\AppData\Local\Programs\Python\Python36-32\lib\multiprocessing\process.py", line 105, in start
  File "C:\...\AppData\Local\Programs\Python\Python36-32\lib\multiprocessing\context.py", line 322, in _Popen
    self._popen = self._Popen(self)
    return Popen(process_obj)
  File "C:\...\AppData\Local\Programs\Python\Python36-32\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
  File "C:\...\AppData\Local\Programs\Python\Python36-32\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\...\AppData\Local\Programs\Python\Python36-32\lib\multiprocessing\context.py", line 322, in _Popen
    reduction.dump(process_obj, to_child)
    return Popen(process_obj)
  File "C:\...\AppData\Local\Programs\Python\Python36-32\lib\multiprocessing\reduction.py", line 60, in dump
  File "C:\...\AppData\Local\Programs\Python\Python36-32\lib\multiprocessing\popen_spawn_win32.py", line 33, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\...\AppData\Local\Programs\Python\Python36-32\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    ForkingPickler(file, protocol).dump(obj)
    _check_not_importing_main()
BrokenPipeError: [Errno 32] Broken pipe
  File "C:\...\AppData\Local\Programs\Python\Python36-32\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
```

**Comment by eichmmar** [comment]
https://github.com/leeroybrun/glacier-vault-remove/pull/35 fixes this issue.
