### ISSUE TITLE
ERROR : [Errno 185090050] _ssl.c:344: error:0B084002:x509 certificate routines:X509_load_cert_crl_file:system lib

### ISSUE THREAD

**Issue by jeberly** [leeroybrun/glacier-vault-remove#8]
Thanks for you lib!  I have been paying for Glacier vaults I don't want for months.  

I am getting the following error when trying to delete my vaults.  It always works on 2nd retry after 2 mins.
https://gist.github.com/jeberly/4f92dd5829b13eb95bb2

Thanks in advance.

in case it matters, boto version 2.38.0, Python 2.7.6

**Comment by leeroybrun** [comment]
Hello, 

Sorry for the delay...

Have you found a solution ?

I've checked online, and it seems that this error can occurs if you are using pyinstaller. Is it the case ? https://github.com/kennethreitz/requests/issues/557#issuecomment-6420819

Or maybe `certifi` is not installed. Can you please try to install it with `pip install certifi` ?
https://github.com/kennethreitz/requests/issues/557#issuecomment-11238323

**Comment by rhamnett** [comment]
Hi getting an error when removing a vault with lots of files (circa 7m)... any help much appreciated.

Traceback (most recent call last):
  File "./removeVault.py", line 92, in <module>
    inventory = json.loads(job.get_output().read())
  File "/usr/local/lib/python2.7/dist-packages/boto-2.38.0-py2.7.egg/boto/glacier/job.py", line 89, in get_output
    byte_range)
  File "/usr/local/lib/python2.7/dist-packages/boto-2.38.0-py2.7.egg/boto/glacier/layer1.py", line 740, in get_job_output
    response_headers=response_headers)
  File "/usr/local/lib/python2.7/dist-packages/boto-2.38.0-py2.7.egg/boto/glacier/layer1.py", line 116, in make_request
    return GlacierResponse(response, response_headers)
  File "/usr/local/lib/python2.7/dist-packages/boto-2.38.0-py2.7.egg/boto/glacier/response.py", line 41, in __init__
    body = json.loads(http_response.read().decode('utf-8'))
  File "/usr/local/lib/python2.7/dist-packages/boto-2.38.0-py2.7.egg/boto/connection.py", line 410, in read
    self._cached_response = http_client.HTTPResponse.read(self)
  File "/usr/lib/python2.7/httplib.py", line 551, in read
    s = self._safe_read(self.length)
  File "/usr/lib/python2.7/httplib.py", line 660, in _safe_read
    raise IncompleteRead(''.join(s), amt)
httplib.IncompleteRead: IncompleteRead(155886763 bytes read, 2697175103 more expected)

**Comment by leeroybrun** [comment]
I'm closing this as I got no news... feel free to post again if you still have an error.
